language: php
dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest
    - REQUIRE=composer require phpro/grumphp:* --no-progress --profile --no-scripts --no-suggest

cache:
  directories:
    - .composer/cache

matrix:
  fast_finish: true

before_install:
  - alias composer=composer\ --no-interaction && composer selfupdate
  - composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES
  - travis_retry $REQUIRE

script:
   - ./vendor/bin/grumphp run
