# Required to run your project under the correct environment.
language: php

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
    - php: nightly

# Commands to be run before your environment runs.
install:
  - composer install --dev --no-interaction --prefer-dist
  - phpenv rehash

script:
  - ./vendor/bin/grumphp run

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always