name: Run grumphp with different versions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
    container:
      image: kanti/buildy:${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-progress --no-scripts -n
      - run: ./vendor/bin/grumphp run
